### ISSUE TITLE
Improve/Simplify deal submission

### ISSUE THREAD

**Issue by DEVxALMIGHTY** [TheRealGD/therealgd#41] opened 2018-03-25 20:30 UTC
1. Select flair, also gives a nice description of flair (description can be removed from mobile)
2. Give price or pecentage (ezpz)
3. Describe the product (what you want)
From there the website will create a title based on this information. The example I gave would set the title as:
[Handgun] $3.50 - Glork 1911 - includes 2 clips and laser/light combo

# Example
![image](https://user-images.githubusercontent.com/37675911/37879615-5ba0ec3e-3041-11e8-8bb4-7fe4af559e34.png)

**Comment by psineur** [comment] 2018-03-25 20:40
Please use https://github.com/TheRealGD/therealgd/blob/develop/docs/overrides.md
Price is sale forum specific, overrides may allow choose which forums this applies from the box, but even if not - it will make it easier to separate sale/non-sale UI later

**Comment by psineur** [comment] 2018-04-25 03:53
Dupe of #14 
Closed

**Closed by psineur** 2018-04-25 03:53 UTC
Labels: TODO, UI, good first issue
