### ISSUE TITLE
Feature/Bug: When editing a comment, user should not be redirected to a new screen. When edited comment is submitted, a comment box briefly appears then disappears.

### ISSUE THREAD

**Issue by waitgain** [TheRealGD/therealgd#133] opened 2018-03-30 04:08 UTC
When I click to edit a comment, I am: 1) brought to a separate screen and 2) when finished editing, I remain on that separate screen.

I think editing should all be done within the comment thread without any redirects.

3) Please also note (at the end of the screen cap) the brief appearance and disappearance of a comment reply box after I click submit to my edited comment.

Please see video "Ticket #133"

**Comment by psineur** [comment] 2018-03-31 00:24
Dupe of #114 and #112

**Closed by psineur** 2018-03-31 00:24 UTC
